language: nix
env:
  # GHC 7.10.3
  # - STACK_RESOLVER=lts-6.35
  # GHC 8.0.2
  # - STACK_RESOLVER=9.21
  # GHC 8.2.2
  - STACK_RESOLVER=lts-11.22
  # GHC 8.4.4
  - STACK_RESOLVER=lts-12.26
  # GHC 8.6.3
  - STACK_RESOLVER=lts-13.10

before_install:
  # configure Nix https://nixos.wiki/wiki/Nix_on_Travis
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'sandbox = true' | sudo tee -a /etc/nix/nix.conf > /dev/null
  # Download and unpack the stack executable https://docs.haskellstack.org/en/stable/travis_ci/#installing-stack
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack build --test --prefetch --coverage --resolver $STACK_RESOLVER

after_script:
  - stack hpc report --all --destdir $(stack path --local-hpc-root)/all/
  - stack exec -- codecov-haskell test-all --tix-dir $(stack path --local-hpc-root)/ --mix-dir $(stack path --dist-dir)/hpc/ --exclude-dir=test --display-report --print-response

cache:
  directories:
  - $HOME/nix.store
  - $HOME/.stack

before_cache:
# cache Nix store https://nixos.wiki/wiki/Nix_on_Travis
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs