language: nix
env:
  # GHC 7.10.3
  - STACK_RESOLVER=lts=6.35
  # GHC 8.0.2
  # - STACK_RESOLVER=9.21
  # GHC 8.2.2
  # - STACK_RESOLVER=lts-11.22
  # GHC 8.4.4
  # - STACK_RESOLVER=lts-12.26
  # GHC 8.6.3
  - STACK_RESOLVER=lts-13.10

# configuring Nix as described here https://nixos.wiki/wiki/Nix_on_Travis
before_install:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'sandbox = true' | sudo tee -a /etc/nix/nix.conf > /dev/null

script:
  - stack build --test --prefetch --resolver $STACK_RESOLVER

# after_script:
#   - dist/build/codecov-haskell/codecov-haskell test-all --exclude-dir=test --display-report --print-response

cache:
  directories:
  - $HOME/nix.store